import { PrismaClient, Role } from "@prisma/client";

const prisma = new PrismaClient();

// Helper to serialize roles for database
function serializeRoles(roles: Role[]): string {
  return JSON.stringify(roles);
}

async function main() {
  // Create or get 3 users
  const user1 = await prisma.user.upsert({
    where: { email: "alon@example.com" },
    update: {
      roles: serializeRoles(["USER"]),
    },
    create: {
      name: "אלון כהן",
      email: "alon@example.com",
      phone: "+972-50-123-4567",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 85,
      isVerified: true,
    },
  });

  const user2 = await prisma.user.upsert({
    where: { email: "sara@example.com" },
    update: {},
    create: {
      name: "שרה לוי",
      email: "sara@example.com",
      phone: "+972-50-234-5678",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 92,
      isVerified: true,
    },
  });

  const user3 = await prisma.user.upsert({
    where: { email: "david@example.com" },
    update: {},
    create: {
      name: "דוד ישראלי",
      email: "david@example.com",
      phone: "+972-50-345-6789",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 78,
      isVerified: false,
    },
  });

  const user4 = await prisma.user.upsert({
    where: { email: "maya@example.com" },
    update: {},
    create: {
      name: "מאיה אברהם",
      email: "maya@example.com",
      phone: "+972-50-456-7890",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 95,
      isVerified: true,
    },
  });

  const user5 = await prisma.user.upsert({
    where: { email: "tom@example.com" },
    update: {},
    create: {
      name: "תום רוזן",
      email: "tom@example.com",
      phone: "+972-50-567-8901",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 88,
      isVerified: true,
    },
  });

  const user6 = await prisma.user.upsert({
    where: { email: "noa@example.com" },
    update: {},
    create: {
      name: "נועה דוד",
      email: "noa@example.com",
      phone: "+972-50-678-9012",
      avatar: "/person.png",
      roles: serializeRoles(["USER"]),
      trustScore: 82,
      isVerified: false,
    },
  });

  const listings = [
    // Premium Cameras
    {
      ownerId: user1.id,
      title: "Canon EOS R5 - Professional Camera",
      description: "High-end mirrorless camera perfect for professional photography. Includes 24-70mm lens, battery, and charger. Excellent condition, barely used.",
      category: "cameras",
      dailyRate: 150,
      depositOverride: 2000,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 12,
    },
    {
      ownerId: user3.id,
      title: "Sony A7III Mirrorless Camera",
      description: "Full-frame mirrorless camera with excellent low-light performance. Includes 50mm f/1.8 lens, two batteries, and memory card.",
      category: "cameras",
      dailyRate: 120,
      depositOverride: 1800,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 25,
    },
    {
      ownerId: user4.id,
      title: "Nikon Z6 II with 24-70mm Lens",
      description: "Professional mirrorless camera with 4K video capabilities. Kit includes lens, battery grip, and professional bag.",
      category: "cameras",
      dailyRate: 140,
      depositOverride: 1900,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 8,
    },
    {
      ownerId: user5.id,
      title: "Fujifilm X-T4 Camera Body",
      description: "Compact mirrorless camera perfect for travel photography. Includes battery, charger, and camera strap.",
      category: "cameras",
      dailyRate: 90,
      depositOverride: 1200,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 15,
    },
    {
      ownerId: user2.id,
      title: "Canon 5D Mark IV DSLR",
      description: "Professional full-frame DSLR camera. Perfect for weddings and events. Includes 24-105mm lens.",
      category: "cameras",
      dailyRate: 130,
      depositOverride: 1700,
      minDays: 3,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: false,
      ratingAvg: 4.5,
      ratingCount: 6,
    },
    // Drones
    {
      ownerId: user1.id,
      title: "DJI Mavic 3 Pro Drone",
      description: "Latest DJI drone with 4K video and obstacle avoidance. Perfect for aerial photography. Includes 3 batteries, charger, and carrying case.",
      category: "drones",
      dailyRate: 200,
      depositOverride: 3000,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: false,
      ratingAvg: 4.9,
      ratingCount: 8,
    },
    {
      ownerId: user1.id,
      title: "DJI Mini 3 Drone",
      description: "Compact and lightweight drone, perfect for travel. Great for beginners and professionals alike. Includes 2 batteries and controller.",
      category: "drones",
      dailyRate: 100,
      depositOverride: 1500,
      minDays: 1,
      photos: JSON.stringify(["/drone.png"]),
      locationText: "Netanya, Israel",
      lat: 32.3320,
      lng: 34.8599,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 18,
    },
    {
      ownerId: user4.id,
      title: "DJI Air 2S Drone",
      description: "Mid-range drone with 5.4K video. Excellent for real estate and event photography. Includes extra propellers and landing pad.",
      category: "drones",
      dailyRate: 150,
      depositOverride: 2200,
      minDays: 2,
      photos: JSON.stringify(["/drone.png", "/drone.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 11,
    },
    {
      ownerId: user6.id,
      title: "DJI Phantom 4 Pro",
      description: "Professional drone with mechanical shutter. Perfect for commercial photography. Includes hard case and multiple batteries.",
      category: "drones",
      dailyRate: 180,
      depositOverride: 2800,
      minDays: 3,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Ashdod, Israel",
      lat: 31.8044,
      lng: 34.6553,
      instantBook: false,
      ratingAvg: 4.6,
      ratingCount: 5,
    },
    // Tools
    {
      ownerId: user2.id,
      title: "Professional Power Drill Set",
      description: "Complete power tool set with drill, impact driver, and various bits. Great for home projects. Includes carrying case.",
      category: "tools",
      dailyRate: 45,
      depositOverride: 500,
      minDays: 1,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 15,
    },
    {
      ownerId: user3.id,
      title: "Heavy Duty Circular Saw",
      description: "Professional circular saw with laser guide. Perfect for cutting wood, metal, and tiles. Includes safety equipment.",
      category: "tools",
      dailyRate: 55,
      depositOverride: 600,
      minDays: 1,
      photos: JSON.stringify(["/drill.png"]),
      locationText: "Beer Sheva, Israel",
      lat: 31.2530,
      lng: 34.7915,
      instantBook: true,
      ratingAvg: 4.4,
      ratingCount: 9,
    },
    {
      ownerId: user5.id,
      title: "Complete Home Renovation Tool Kit",
      description: "Everything for home renovation: hammer drill, angle grinder, jigsaw, and more. Professional grade tools.",
      category: "tools",
      dailyRate: 75,
      depositOverride: 800,
      minDays: 2,
      photos: JSON.stringify(["/drill.png", "/drill.png", "/drill.png"]),
      locationText: "Petah Tikva, Israel",
      lat: 32.0889,
      lng: 34.8564,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 12,
    },
    {
      ownerId: user6.id,
      title: "Cordless Impact Wrench Set",
      description: "High-torque impact wrench for automotive work. Includes multiple socket sizes and battery charger.",
      category: "tools",
      dailyRate: 50,
      depositOverride: 550,
      minDays: 1,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Rishon LeZion, Israel",
      lat: 31.9730,
      lng: 34.7925,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 7,
    },
    {
      ownerId: user1.id,
      title: "Professional Tile Cutter",
      description: "Electric tile cutter with water cooling system. Perfect for bathroom and kitchen renovations.",
      category: "tools",
      dailyRate: 60,
      depositOverride: 700,
      minDays: 1,
      photos: JSON.stringify(["/drill.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.3,
      ratingCount: 4,
    },
    // DJ Gear
    {
      ownerId: user2.id,
      title: "Pioneer DJ Controller DDJ-1000",
      description: "Professional 4-channel DJ controller with full-size jog wheels. Perfect for events. Includes USB cable and carrying case.",
      category: "djGear",
      dailyRate: 120,
      depositOverride: 1500,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 10,
    },
    {
      ownerId: user4.id,
      title: "Pioneer CDJ-2000NXS2 Players",
      description: "Professional CDJ players with Rekordbox support. Includes two players and mixer. Perfect for clubs and events.",
      category: "djGear",
      dailyRate: 250,
      depositOverride: 4000,
      minDays: 3,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 4.9,
      ratingCount: 6,
    },
    {
      ownerId: user5.id,
      title: "Numark Mixtrack Pro 3",
      description: "Entry-level DJ controller perfect for beginners. Includes software license and tutorial videos.",
      category: "djGear",
      dailyRate: 80,
      depositOverride: 900,
      minDays: 1,
      photos: JSON.stringify(["/ladder.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 13,
    },
    {
      ownerId: user6.id,
      title: "Allen & Heath Xone:92 Mixer",
      description: "Professional 4-channel analog mixer with high-quality filters. Perfect for techno and house music.",
      category: "djGear",
      dailyRate: 100,
      depositOverride: 1200,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 9,
    },
    // Camping Gear
    {
      ownerId: user3.id,
      title: "4-Person Camping Tent",
      description: "Spacious waterproof tent with rainfly. Easy setup, perfect for weekend camping trips. Includes groundsheet and pegs.",
      category: "camping",
      dailyRate: 60,
      depositOverride: 800,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Eilat, Israel",
      lat: 29.5577,
      lng: 34.9519,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 20,
    },
    {
      ownerId: user2.id,
      title: "Complete Camping Gear Set",
      description: "Everything you need: tent, sleeping bags, camping stove, cooler, and more. Perfect for a week-long trip.",
      category: "camping",
      dailyRate: 80,
      depositOverride: 1000,
      minDays: 3,
      photos: JSON.stringify(["/ladder.png", "/shnork.png", "/ladder.png"]),
      locationText: "Beer Sheva, Israel",
      lat: 31.2530,
      lng: 34.7915,
      instantBook: false,
      ratingAvg: 4.6,
      ratingCount: 14,
    },
    {
      ownerId: user3.id,
      title: "Snorkeling Gear Set",
      description: "Complete snorkeling set with mask, fins, and snorkel. Perfect for Red Sea diving. All sizes available.",
      category: "camping",
      dailyRate: 50,
      depositOverride: 400,
      minDays: 1,
      photos: JSON.stringify(["/shnork.png", "/shnork.png"]),
      locationText: "Eilat, Israel",
      lat: 29.5577,
      lng: 34.9519,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 11,
    },
    {
      ownerId: user4.id,
      title: "6-Person Family Camping Tent",
      description: "Large family tent with separate rooms. Waterproof and wind-resistant. Perfect for extended camping trips.",
      category: "camping",
      dailyRate: 70,
      depositOverride: 900,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png"]),
      locationText: "Tiberias, Israel",
      lat: 32.7959,
      lng: 35.5308,
      instantBook: true,
      ratingAvg: 4.4,
      ratingCount: 8,
    },
    {
      ownerId: user5.id,
      title: "Portable Camping Stove & Cookware",
      description: "Complete cooking setup for camping: gas stove, pots, pans, and utensils. Everything you need for outdoor cooking.",
      category: "camping",
      dailyRate: 40,
      depositOverride: 300,
      minDays: 1,
      photos: JSON.stringify(["/shnork.png", "/shnork.png", "/shnork.png"]),
      locationText: "Netanya, Israel",
      lat: 32.3320,
      lng: 34.8599,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 16,
    },
    {
      ownerId: user6.id,
      title: "Hiking Backpack & Gear",
      description: "60L hiking backpack with sleeping bag, mat, and hiking poles. Perfect for day trips and overnight hikes.",
      category: "camping",
      dailyRate: 55,
      depositOverride: 500,
      minDays: 1,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Zichron Yaakov, Israel",
      lat: 32.5694,
      lng: 34.9500,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 7,
    },
    // Sports Equipment
    {
      ownerId: user1.id,
      title: "Tennis Racket Pro",
      description: "Professional tennis racket with premium strings. Perfect for competitive play. Includes racket cover and extra strings.",
      category: "sports",
      dailyRate: 35,
      depositOverride: 300,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 7,
    },
    {
      ownerId: user2.id,
      title: "Professional Badminton Set",
      description: "Complete badminton set with rackets, shuttlecocks, and net. Perfect for family fun or training.",
      category: "sports",
      dailyRate: 30,
      depositOverride: 250,
      minDays: 1,
      photos: JSON.stringify(["/racket.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 5,
    },
    {
      ownerId: user4.id,
      title: "Table Tennis Set",
      description: "Portable table tennis set with paddles, balls, and net. Great for indoor entertainment.",
      category: "sports",
      dailyRate: 40,
      depositOverride: 350,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png", "/racket.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 9,
    },
    {
      ownerId: user5.id,
      title: "Basketball Hoop & Ball",
      description: "Portable basketball hoop with official size ball. Perfect for driveway or park games.",
      category: "sports",
      dailyRate: 45,
      depositOverride: 400,
      minDays: 2,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: false,
      ratingAvg: 4.4,
      ratingCount: 3,
    },
    {
      ownerId: user6.id,
      title: "Soccer Goal & Equipment",
      description: "Portable soccer goal with balls and cones. Perfect for practice sessions and kids' games.",
      category: "sports",
      dailyRate: 50,
      depositOverride: 450,
      minDays: 1,
      photos: JSON.stringify(["/racket.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 6,
    },
    // Additional listings for variety
    {
      ownerId: user1.id,
      title: "GoPro Hero 11 Black",
      description: "Action camera with 5.3K video and HyperSmooth stabilization. Perfect for sports and adventures. Includes mounts and accessories.",
      category: "cameras",
      dailyRate: 70,
      depositOverride: 800,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 22,
    },
    {
      ownerId: user3.id,
      title: "Canon EF 70-200mm f/2.8 Lens",
      description: "Professional telephoto lens perfect for sports and wildlife photography. Excellent condition, includes lens hood and case.",
      category: "cameras",
      dailyRate: 85,
      depositOverride: 1500,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 10,
    },
    {
      ownerId: user4.id,
      title: "DJI Osmo Action Camera",
      description: "Dual-screen action camera with 4K HDR video. Great alternative to GoPro. Includes waterproof housing.",
      category: "cameras",
      dailyRate: 60,
      depositOverride: 700,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 8,
    },
    {
      ownerId: user2.id,
      title: "Autel EVO Lite+ Drone",
      description: "Professional drone with 6K video and 40-minute flight time. Includes 3 batteries and hard case.",
      category: "drones",
      dailyRate: 170,
      depositOverride: 2600,
      minDays: 2,
      photos: JSON.stringify(["/drone.png", "/drone.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 4,
    },
    {
      ownerId: user5.id,
      title: "Parrot Anafi Drone",
      description: "Compact foldable drone with 4K HDR video. Perfect for travel photography. Includes carrying case.",
      category: "drones",
      dailyRate: 110,
      depositOverride: 1800,
      minDays: 1,
      photos: JSON.stringify(["/drone.png"]),
      locationText: "Netanya, Israel",
      lat: 32.3320,
      lng: 34.8599,
      instantBook: true,
      ratingAvg: 4.4,
      ratingCount: 7,
    },
    {
      ownerId: user6.id,
      title: "Electric Chainsaw",
      description: "Cordless electric chainsaw with battery and charger. Perfect for tree trimming and firewood. Includes safety gear.",
      category: "tools",
      dailyRate: 65,
      depositOverride: 750,
      minDays: 1,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Beer Sheva, Israel",
      lat: 31.2530,
      lng: 34.7915,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 6,
    },
    {
      ownerId: user1.id,
      title: "Pressure Washer",
      description: "High-pressure washer perfect for cleaning driveways, decks, and vehicles. Includes various nozzles and extension wand.",
      category: "tools",
      dailyRate: 55,
      depositOverride: 650,
      minDays: 1,
      photos: JSON.stringify(["/drill.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 11,
    },
    {
      ownerId: user3.id,
      title: "Roland DJ-808 Controller",
      description: "All-in-one DJ controller with built-in drum machine. Perfect for live performances. Includes software and cables.",
      category: "djGear",
      dailyRate: 140,
      depositOverride: 1800,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 5,
    },
    {
      ownerId: user4.id,
      title: "Traktor Kontrol S4 MK3",
      description: "Professional 4-channel DJ controller with motorized platters. Includes Traktor Pro software license.",
      category: "djGear",
      dailyRate: 130,
      depositOverride: 1700,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 8,
    },
    {
      ownerId: user5.id,
      title: "Inflatable Kayak Set",
      description: "2-person inflatable kayak with paddles and pump. Perfect for river and lake adventures. Easy to transport.",
      category: "camping",
      dailyRate: 90,
      depositOverride: 1100,
      minDays: 2,
      photos: JSON.stringify(["/shnork.png", "/shnork.png", "/shnork.png", "/shnork.png"]),
      locationText: "Tiberias, Israel",
      lat: 32.7959,
      lng: 35.5308,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 9,
    },
    {
      ownerId: user6.id,
      title: "Portable Generator",
      description: "2000W portable generator perfect for camping and power outages. Includes fuel can and extension cord.",
      category: "camping",
      dailyRate: 85,
      depositOverride: 950,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Ashdod, Israel",
      lat: 31.8044,
      lng: 34.6553,
      instantBook: false,
      ratingAvg: 4.5,
      ratingCount: 5,
    },
    {
      ownerId: user2.id,
      title: "Golf Club Set",
      description: "Complete golf club set with bag, driver, irons, and putter. Perfect for weekend golfers.",
      category: "sports",
      dailyRate: 60,
      depositOverride: 600,
      minDays: 2,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: false,
      ratingAvg: 4.6,
      ratingCount: 4,
    },
    {
      ownerId: user1.id,
      title: "Yoga Mat & Equipment Set",
      description: "Premium yoga mat with blocks, straps, and bolsters. Perfect for home practice or classes.",
      category: "sports",
      dailyRate: 25,
      depositOverride: 200,
      minDays: 1,
      photos: JSON.stringify(["/racket.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 12,
    },
    // New listings with 0 ratings for testing
    {
      ownerId: user4.id,
      title: "Canon RF 85mm f/1.2 Lens",
      description: "Premium portrait lens with incredible bokeh. Perfect for professional portrait photography.",
      category: "cameras",
      dailyRate: 160,
      depositOverride: 2500,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: false,
      ratingAvg: 0,
      ratingCount: 0,
    },
    {
      ownerId: user5.id,
      title: "DJI FPV Drone",
      description: "First-person view racing drone with goggles. Extreme speed and agility. Includes FPV goggles and controller.",
      category: "drones",
      dailyRate: 190,
      depositOverride: 3200,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 0,
      ratingCount: 0,
    },
    {
      ownerId: user6.id,
      title: "Welding Machine Set",
      description: "Professional MIG welder with safety equipment. Perfect for metalworking projects. Includes helmet and gloves.",
      category: "tools",
      dailyRate: 95,
      depositOverride: 1200,
      minDays: 3,
      photos: JSON.stringify(["/drill.png", "/drill.png", "/drill.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: false,
      ratingAvg: 0,
      ratingCount: 0,
    },
    // Additional mock listings for UX/UI design
    // Cameras - Budget to Premium
    {
      ownerId: user1.id,
      title: "Sony Alpha 7C Compact Full-Frame",
      description: "Ultra-compact full-frame mirrorless camera. Perfect for travel photographers who want professional quality in a small package.",
      category: "cameras",
      dailyRate: 110,
      depositOverride: 1600,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 31,
    },
    {
      ownerId: user2.id,
      title: "Olympus OM-D E-M10 Mark IV",
      description: "Entry-level mirrorless camera with excellent image stabilization. Great for beginners and travel photography.",
      category: "cameras",
      dailyRate: 65,
      depositOverride: 900,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: true,
      ratingAvg: 4.4,
      ratingCount: 9,
    },
    {
      ownerId: user3.id,
      title: "Panasonic Lumix GH6",
      description: "Professional video-focused camera with 5.7K recording. Perfect for content creators and videographers.",
      category: "cameras",
      dailyRate: 125,
      depositOverride: 1700,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 14,
    },
    {
      ownerId: user4.id,
      title: "Leica Q2 Monochrom",
      description: "Premium black and white camera with exceptional image quality. For serious photographers who appreciate monochrome art.",
      category: "cameras",
      dailyRate: 180,
      depositOverride: 3500,
      minDays: 3,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 5.0,
      ratingCount: 3,
    },
    // Drones - Various Models
    {
      ownerId: user2.id,
      title: "DJI Mini 2 SE",
      description: "Affordable compact drone perfect for beginners. Easy to fly with automatic features. Great for travel and social media.",
      category: "drones",
      dailyRate: 80,
      depositOverride: 1200,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Netanya, Israel",
      lat: 32.3320,
      lng: 34.8599,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 19,
    },
    {
      ownerId: user3.id,
      title: "DJI Avata FPV Drone",
      description: "Cinewhoop-style FPV drone with goggles. Perfect for indoor and outdoor cinematic shots. Includes motion controller.",
      category: "drones",
      dailyRate: 160,
      depositOverride: 2400,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 6,
    },
    {
      ownerId: user5.id,
      title: "Autel EVO II Pro 6K",
      description: "Professional drone with 6K video and 1-inch sensor. Excellent for commercial photography and videography.",
      category: "drones",
      dailyRate: 220,
      depositOverride: 3500,
      minDays: 2,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 4.9,
      ratingCount: 7,
    },
    // Tools - Various Types
    {
      ownerId: user1.id,
      title: "Bosch Professional Router Set",
      description: "High-precision wood router with multiple bits. Perfect for furniture making and detailed woodwork.",
      category: "tools",
      dailyRate: 70,
      depositOverride: 850,
      minDays: 2,
      photos: JSON.stringify(["/drill.png", "/drill.png", "/drill.png"]),
      locationText: "Petah Tikva, Israel",
      lat: 32.0889,
      lng: 34.8564,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 8,
    },
    {
      ownerId: user2.id,
      title: "Makita Cordless Drill Driver Set",
      description: "18V cordless drill with two batteries and charger. Includes various drill bits and screwdriver attachments.",
      category: "tools",
      dailyRate: 40,
      depositOverride: 450,
      minDays: 1,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Rishon LeZion, Israel",
      lat: 31.9730,
      lng: 34.7925,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 22,
    },
    {
      ownerId: user4.id,
      title: "Festool Track Saw System",
      description: "Premium track saw for precise straight cuts. Perfect for cabinet making and fine woodworking.",
      category: "tools",
      dailyRate: 100,
      depositOverride: 1400,
      minDays: 2,
      photos: JSON.stringify(["/drill.png", "/drill.png", "/drill.png", "/drill.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: false,
      ratingAvg: 4.9,
      ratingCount: 5,
    },
    {
      ownerId: user6.id,
      title: "Dewalt Miter Saw Stand",
      description: "Professional compound miter saw with stand. Perfect for trim work and framing projects.",
      category: "tools",
      dailyRate: 85,
      depositOverride: 1000,
      minDays: 2,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Ashdod, Israel",
      lat: 31.8044,
      lng: 34.6553,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 10,
    },
    // DJ Gear - Various Equipment
    {
      ownerId: user1.id,
      title: "Denon DJ Prime 4 Standalone",
      description: "4-channel standalone DJ controller with built-in screen. No laptop needed. Perfect for mobile DJs.",
      category: "djGear",
      dailyRate: 180,
      depositOverride: 2500,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 12,
    },
    {
      ownerId: user3.id,
      title: "Reloop RMX-90 DJ Mixer",
      description: "Professional 4-channel rotary mixer with high-quality sound. Perfect for house and techno DJs.",
      category: "djGear",
      dailyRate: 110,
      depositOverride: 1300,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 7,
    },
    {
      ownerId: user5.id,
      title: "Native Instruments Traktor Kontrol S8",
      description: "Professional DJ controller with touch strips and remix decks. Includes Traktor Pro 3 software.",
      category: "djGear",
      dailyRate: 150,
      depositOverride: 2000,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 9,
    },
    {
      ownerId: user6.id,
      title: "Pioneer DJM-900NXS2 Mixer",
      description: "Professional 4-channel club mixer with effects. Industry standard for clubs and festivals.",
      category: "djGear",
      dailyRate: 200,
      depositOverride: 3000,
      minDays: 3,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 5.0,
      ratingCount: 4,
    },
    // Camping - Various Equipment
    {
      ownerId: user1.id,
      title: "Coleman Instant Tent 6-Person",
      description: "Quick setup tent that assembles in 60 seconds. Perfect for families and groups. Waterproof and wind-resistant.",
      category: "camping",
      dailyRate: 65,
      depositOverride: 850,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Eilat, Israel",
      lat: 29.5577,
      lng: 34.9519,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 17,
    },
    {
      ownerId: user2.id,
      title: "REI Co-op Half Dome 2 Plus Tent",
      description: "Lightweight backpacking tent for two people. Easy to carry and quick to set up. Perfect for hiking trips.",
      category: "camping",
      dailyRate: 55,
      depositOverride: 700,
      minDays: 1,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Tiberias, Israel",
      lat: 32.7959,
      lng: 35.5308,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 13,
    },
    {
      ownerId: user4.id,
      title: "Yeti Tundra 65 Cooler",
      description: "Premium rotomolded cooler that keeps ice for days. Perfect for extended camping trips and outdoor events.",
      category: "camping",
      dailyRate: 45,
      depositOverride: 600,
      minDays: 1,
      photos: JSON.stringify(["/shnork.png", "/shnork.png", "/shnork.png"]),
      locationText: "Netanya, Israel",
      lat: 32.3320,
      lng: 34.8599,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 21,
    },
    {
      ownerId: user5.id,
      title: "Jetboil Flash Cooking System",
      description: "Ultra-fast portable stove that boils water in 100 seconds. Perfect for backpacking and camping.",
      category: "camping",
      dailyRate: 35,
      depositOverride: 350,
      minDays: 1,
      photos: JSON.stringify(["/shnork.png", "/shnork.png"]),
      locationText: "Zichron Yaakov, Israel",
      lat: 32.5694,
      lng: 34.9500,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 15,
    },
    {
      ownerId: user6.id,
      title: "Big Agnes Air Core Ultra Sleeping Pad",
      description: "Lightweight inflatable sleeping pad with excellent insulation. Perfect for cold weather camping.",
      category: "camping",
      dailyRate: 30,
      depositOverride: 300,
      minDays: 1,
      photos: JSON.stringify(["/ladder.png"]),
      locationText: "Beer Sheva, Israel",
      lat: 31.2530,
      lng: 34.7915,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 11,
    },
    // Sports - Various Equipment
    {
      ownerId: user1.id,
      title: "Wilson Pro Staff Tennis Racket",
      description: "Professional tennis racket used by top players. Perfect for advanced players seeking precision and control.",
      category: "sports",
      dailyRate: 40,
      depositOverride: 400,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png", "/racket.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 16,
    },
    {
      ownerId: user2.id,
      title: "Babolat Pure Drive Tennis Racket",
      description: "Powerful tennis racket perfect for aggressive players. Includes vibration dampener and overgrip.",
      category: "sports",
      dailyRate: 38,
      depositOverride: 380,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 9,
    },
    {
      ownerId: user3.id,
      title: "Cornilleau 500X Table Tennis Table",
      description: "Professional table tennis table with wheels for easy storage. Perfect for tournaments and serious players.",
      category: "sports",
      dailyRate: 50,
      depositOverride: 500,
      minDays: 2,
      photos: JSON.stringify(["/racket.png", "/racket.png", "/racket.png", "/racket.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: false,
      ratingAvg: 4.7,
      ratingCount: 6,
    },
    {
      ownerId: user4.id,
      title: "Spalding NBA Official Basketball",
      description: "Official size and weight basketball. Perfect for practice and games. Includes pump and needle.",
      category: "sports",
      dailyRate: 20,
      depositOverride: 150,
      minDays: 1,
      photos: JSON.stringify(["/racket.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 8,
    },
    {
      ownerId: user5.id,
      title: "Adidas Telstar Football",
      description: "Official match football with classic design. Perfect for training and matches. Includes ball pump.",
      category: "sports",
      dailyRate: 25,
      depositOverride: 200,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 12,
    },
    {
      ownerId: user6.id,
      title: "Nike Air Zoom Vapor Tennis Shoes",
      description: "Professional tennis shoes with excellent court grip. Size 42-45 available. Perfect for competitive play.",
      category: "sports",
      dailyRate: 30,
      depositOverride: 250,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png", "/racket.png"]),
      locationText: "Rishon LeZion, Israel",
      lat: 31.9730,
      lng: 34.7925,
      instantBook: true,
      ratingAvg: 4.4,
      ratingCount: 5,
    },
    // More cameras for variety
    {
      ownerId: user1.id,
      title: "Canon EOS R6 Mark II",
      description: "Versatile full-frame mirrorless camera with excellent autofocus. Perfect for sports and wildlife photography.",
      category: "cameras",
      dailyRate: 135,
      depositOverride: 2100,
      minDays: 2,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 18,
    },
    {
      ownerId: user3.id,
      title: "Fujifilm X100V",
      description: "Premium compact camera with fixed 23mm lens. Perfect for street photography and travel. Beautiful retro design.",
      category: "cameras",
      dailyRate: 100,
      depositOverride: 1400,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png", "/Cam.png"]),
      locationText: "Ramat Gan, Israel",
      lat: 32.0820,
      lng: 34.8100,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 24,
    },
    {
      ownerId: user5.id,
      title: "Sony A6400 with 18-135mm Lens",
      description: "APS-C mirrorless camera with excellent video capabilities. Great for vloggers and content creators.",
      category: "cameras",
      dailyRate: 95,
      depositOverride: 1300,
      minDays: 1,
      photos: JSON.stringify(["/Cam.png", "/Cam.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 16,
    },
    // More drones
    {
      ownerId: user2.id,
      title: "DJI Air 2S Fly More Combo",
      description: "Complete drone package with 3 batteries, charging hub, and carrying case. Perfect for extended shooting sessions.",
      category: "drones",
      dailyRate: 145,
      depositOverride: 2300,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 20,
    },
    {
      ownerId: user4.id,
      title: "DJI Mini 4 Pro",
      description: "Latest compact drone with 4K HDR video and obstacle sensing. Perfect for travel and social media content.",
      category: "drones",
      dailyRate: 115,
      depositOverride: 1700,
      minDays: 1,
      photos: JSON.stringify(["/drone.png", "/drone.png", "/drone.png"]),
      locationText: "Jerusalem, Israel",
      lat: 31.7683,
      lng: 35.2137,
      instantBook: true,
      ratingAvg: 4.9,
      ratingCount: 15,
    },
    // More tools
    {
      ownerId: user1.id,
      title: "Milwaukee M18 Fuel Impact Driver",
      description: "High-torque cordless impact driver with brushless motor. Perfect for construction and automotive work.",
      category: "tools",
      dailyRate: 48,
      depositOverride: 500,
      minDays: 1,
      photos: JSON.stringify(["/drill.png", "/drill.png"]),
      locationText: "Petah Tikva, Israel",
      lat: 32.0889,
      lng: 34.8564,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 14,
    },
    {
      ownerId: user3.id,
      title: "Ryobi One+ 18V Tool Combo Kit",
      description: "Complete cordless tool set with drill, circular saw, impact driver, and more. Great value for DIY projects.",
      category: "tools",
      dailyRate: 65,
      depositOverride: 750,
      minDays: 2,
      photos: JSON.stringify(["/drill.png", "/drill.png", "/drill.png", "/drill.png"]),
      locationText: "Rishon LeZion, Israel",
      lat: 31.9730,
      lng: 34.7925,
      instantBook: true,
      ratingAvg: 4.5,
      ratingCount: 11,
    },
    // More DJ gear
    {
      ownerId: user2.id,
      title: "Pioneer DJ XDJ-RX3",
      description: "All-in-one standalone DJ system with 7-inch touchscreen. No laptop required. Perfect for mobile DJs.",
      category: "djGear",
      dailyRate: 170,
      depositOverride: 2400,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: false,
      ratingAvg: 4.9,
      ratingCount: 8,
    },
    {
      ownerId: user4.id,
      title: "Rane Seventy-Two Mixer",
      description: "Professional 4-channel mixer with Serato DJ Pro integration. Perfect for scratch DJs and turntablists.",
      category: "djGear",
      dailyRate: 120,
      depositOverride: 1600,
      minDays: 2,
      photos: JSON.stringify(["/ladder.png", "/ladder.png"]),
      locationText: "Haifa, Israel",
      lat: 32.7940,
      lng: 34.9896,
      instantBook: false,
      ratingAvg: 4.8,
      ratingCount: 6,
    },
    // More camping gear
    {
      ownerId: user1.id,
      title: "MSR Hubba Hubba NX 2-Person Tent",
      description: "Lightweight backpacking tent for two. Easy setup and excellent weather protection. Perfect for hiking.",
      category: "camping",
      dailyRate: 58,
      depositOverride: 750,
      minDays: 1,
      photos: JSON.stringify(["/ladder.png", "/ladder.png", "/ladder.png"]),
      locationText: "Tiberias, Israel",
      lat: 32.7959,
      lng: 35.5308,
      instantBook: true,
      ratingAvg: 4.8,
      ratingCount: 19,
    },
    {
      ownerId: user3.id,
      title: "Therm-a-Rest NeoAir XTherm Sleeping Pad",
      description: "Ultra-lightweight sleeping pad with excellent R-value. Perfect for cold weather camping and mountaineering.",
      category: "camping",
      dailyRate: 32,
      depositOverride: 320,
      minDays: 1,
      photos: JSON.stringify(["/shnork.png", "/shnork.png"]),
      locationText: "Eilat, Israel",
      lat: 29.5577,
      lng: 34.9519,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 10,
    },
    // More sports equipment
    {
      ownerId: user1.id,
      title: "Head Speed Pro Tennis Racket",
      description: "Professional tennis racket with graphene technology. Perfect for aggressive baseline players.",
      category: "sports",
      dailyRate: 42,
      depositOverride: 420,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png", "/racket.png"]),
      locationText: "Tel Aviv, Israel",
      lat: 32.0853,
      lng: 34.7818,
      instantBook: true,
      ratingAvg: 4.7,
      ratingCount: 13,
    },
    {
      ownerId: user4.id,
      title: "Wilson Blade 98 Tennis Racket",
      description: "Control-oriented tennis racket perfect for precision players. Includes vibration dampener.",
      category: "sports",
      dailyRate: 39,
      depositOverride: 390,
      minDays: 1,
      photos: JSON.stringify(["/racket.png", "/racket.png"]),
      locationText: "Herzliya, Israel",
      lat: 32.1624,
      lng: 34.8447,
      instantBook: true,
      ratingAvg: 4.6,
      ratingCount: 7,
    },
  ];

  // Clear existing listings first
  await prisma.listing.deleteMany({});

  for (const listing of listings) {
    await prisma.listing.create({
      data: {
        ownerId: listing.ownerId,
        title: listing.title,
        description: listing.description,
        category: listing.category,
        pricePerDay: listing.dailyRate,
        deposit: listing.depositOverride,
        photos: listing.photos,
        locationText: listing.locationText,
        lat: listing.lat,
        lng: listing.lng,
        instantBook: listing.instantBook,
        ratingAvg: listing.ratingAvg,
        ratingCount: listing.ratingCount,
        status: "APPROVED", // Auto-approve seed listings
      },
    });
  }

  // Create admin user (first user is ADMIN)
  const admin = await prisma.user.upsert({
    where: { email: "admin@lendly.com" },
    update: {
      roles: serializeRoles(["ADMIN"]),
    },
    create: {
      name: "Admin User",
      email: "admin@lendly.com",
      phone: "+972-50-000-0000",
      roles: serializeRoles(["ADMIN"]),
      trustScore: 100,
      isVerified: true,
    },
  });

  // Create default Rules
  await prisma.rules.upsert({
    where: { id: "1" },
    update: {},
    create: {
      id: "1",
      baseDepositPct: 0.1,
      minDeposit: 100,
      maxDeposit: 10000,
      insuranceDaily: 50,
      incidentMultiplier: 1.5,
      ownerTrustMultiplier: 1.0,
      renterTrustMultiplier: 1.0,
    },
  });

  console.log("Seed data created successfully!");
  console.log("Admin user created: admin@lendly.com");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

